"""
Turn the public star and constellation catalogues into something small enough
to ship.

Source: https://github.com/ofrohn/d3-celestial (BSD-3, Olaf Frohn), which
packages the standard astronomical catalogues as GeoJSON. Stars carry a real
right ascension, declination, visual magnitude and B-V colour index; the
constellation file carries the conventional stick figures.

The raw star file is 656 kB of JSON objects. Nothing here needs that: four
numbers per star, scaled to integers and flattened into one array, is the same
information in a fifth of the space and parses faster besides.

    python3 scripts/make-star-catalog.py

Cut at the file's own limit, magnitude 6.0 — the naked-eye limit under a
genuinely dark sky. 5.5 was tried first and is the more defensible number for
an average night, but it puts only ~610 stars in frame, and a real sky at that
depth is visibly thinner than the stylised field it replaced. The extra half
magnitude nearly doubles the count for about 40 kB.
"""
import json, pathlib, urllib.request

STARS = "https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/stars.6.json"
LINES = "https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/constellations.lines.json"
MAG_LIMIT = 6.0

root = pathlib.Path(__file__).resolve().parent.parent
out = root / "src/constants/starCatalog.js"


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as r:
        return json.load(r)


def wrap(ra):
    """The source stores right ascension as -180..180; 0..360 is easier to reason about."""
    return ra + 360 if ra < 0 else ra


stars = fetch(STARS)
flat = []
for f in stars["features"]:
    mag = f["properties"].get("mag")
    if not isinstance(mag, (int, float)) or mag > MAG_LIMIT:
        continue
    ra, dec = f["geometry"]["coordinates"]
    try:
        bv = float(f["properties"].get("bv"))
    except (TypeError, ValueError):
        bv = 0.65  # roughly solar; the safe default for a star with no colour recorded
    # Hundredths throughout. 0.01 degrees is 36 arcseconds, far finer than a
    # pixel at any sane zoom, and integers compress better than decimals.
    flat += [
        round(wrap(ra) * 100),
        round(dec * 100),
        round(mag * 100),
        round(max(-0.4, min(2.0, bv)) * 100),
    ]

lines = fetch(LINES)
figures = []
for f in lines["features"]:
    for segment in f["geometry"]["coordinates"]:
        # Tenths are plenty for a stick figure, and it halves the digits.
        figures.append([[round(wrap(ra) * 10), round(dec * 10)] for ra, dec in segment])

body = f"""// GENERATED by scripts/make-star-catalog.py — do not edit by hand.
//
// Real stars. Positions, magnitudes and colours come from the standard
// astronomical catalogues, packaged by d3-celestial (BSD-3, Olaf Frohn):
// https://github.com/ofrohn/d3-celestial
//
// STARS is flat and scaled to integers: [ra, dec, mag, bv] per star, every
// value multiplied by 100. Objects would be five times the size for the same
// four numbers, and this parses as one array rather than {len(flat) // 4}
// allocations.
//
//   ra   0..36000     right ascension, hundredths of a degree
//   dec  -9000..9000  declination
//   mag  -144..600    visual magnitude. Lower is brighter: Sirius is -144.
//   bv   -40..200     B-V colour index. Negative is blue-hot, positive is red-cool.
//
// Cut at magnitude 6.0 — the naked-eye limit under a dark sky. {len(flat) // 4} stars.
// Int32, not Int16. Right ascension in hundredths reaches 36000 and Int16
// stops at 32767, so 222 stars near the end of the sky silently wrapped to
// negative and landed on the opposite side of it.
export const STARS = Int32Array.from([{",".join(str(v) for v in flat)}]);

export const STAR_STRIDE = 4;
export const STAR_COUNT = {len(flat) // 4};

// The conventional constellation figures, in tenths of a degree. Each entry is
// one unbroken run of points; a constellation is usually several.
export const CONSTELLATION_LINES = {json.dumps(figures, separators=(",", ":"))};
"""

out.write_text(body)
print(f"  {out.relative_to(root)}")
print(f"  {len(flat) // 4} stars, {len(figures)} constellation segments, {out.stat().st_size / 1024:.0f} kB raw")
